# Generated by Django 2.2.7 on 2019-11-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_costs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costs',
            new_name='Cost',
        ),
    ]
