# Generated by Django 2.2.7 on 2019-11-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_auto_20191118_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='slug',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.FloatField(default=0),
        ),
    ]
