# Generated by Django 2.2.7 on 2019-11-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0005_auto_20191118_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='limit',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='category',
            name='total_expense',
            field=models.FloatField(default=0),
        ),
    ]
