# Generated by Django 2.2.7 on 2019-12-03 17:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0006_auto_20191120_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
