# Generated by Django 2.2.7 on 2019-12-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0007_auto_20191203_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='total_expense',
        ),
    ]
