# Generated by Django 2.2.7 on 2019-12-11 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0008_remove_category_total_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, error_messages={'min_value': 'Invalid amount'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='limit',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.DecimalField(decimal_places=2, error_messages={'min_value': 'Invalid payment amount'}, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
