# Generated by Django 2.2.7 on 2019-12-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0009_auto_20191211_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ware',
            new_name='Wage',
        ),
    ]
